apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claim-api.fullname" . }}
  labels:
    {{- include "claim-api.labels" . | nindent 4 }}
data:
  CLAIM_CONTRACT_ADDRESS: {{ .Values.app.claimContractAddress | quote }}
  SERVER_PORT: {{ .Values.app.serverPort | quote }}
  DB_HOST: {{ .Values.app.dbHost | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_NAME: {{ .Values.app.dbName | quote }}