app:
  environment: prod
  dbHost: 10.39.112.4
  dbName: delegation
  queueHost: 10.39.114.21
  stakingContractAddress: "0x7Af59Ea121a8Da8e49d2d44856feB7761561995b"
  mainnetEndpoint: "https://rpc.mainnet.taraxa.io"
  testnetEndpoint: "https://rpc.testnet.taraxa.io"
  mainnetExplorerUrl: "https://explorer.mainnet.taraxa.io"
  testnetExplorerUrl: "https://explorer.testnet.taraxa.io"

image:
  repository: taraxa/delegation
  tag: "latest"

ingress:
  hosts:
    - host: api-delegation.community.taraxa.io
  tls:
    - secretName: wild-community-taraxa-io-tls
      hosts:
        - api-delegation.community.taraxa.io

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 400m
    memory: 750Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-prod