workerReplicaCount: 1

app:
  environment: qa
  dbHost: 10.39.112.3
  dbDelegationName: delegation
  dbCommunityName: taraxa-community-qa
  queueHost: 10.39.114.11
  stakingContractAddress: "0x7Af59Ea121a8Da8e49d2d44856feB7761561995b"
  mainnetEndpoint: "https://rpc.mainnet.taraxa.io"
  testnetEndpoint: "https://rpc.testnet.taraxa.io"
  mainnetIndexerUrl: "https://indexer.mainnet.taraxa.io"
  testnetIndexerUrl: "https://indexer.testnet.taraxa.io"
  indexerStakingUrl: http://qa-taraxa-indexer:8000/subgraphs/name/taraxa_project/staking
  testnetOwnNodes:
    - "0x18551e353aa65bc0ffbdf9d93b7ad4a8fe29cf95"
    - "0xc578bb5fc3dac3e96a8c4cb126c71d2dc9082817"
    - "0x5c9afb23fba3967ca6102fb60c9949f6a38cd9e8"
    - "0x403480c2b2ade0851c62bd1ff7a594c416aff7ce"
    - "0x5042fa2711fe547e46c2f64852fdaa5982c80697"
    - "0x6258d8f51ea17e873f69a2a978fe311fd95743dd"


image:
  repository: gcr.io/jovial-meridian-249123/taraxa/delegation-develop
  tag: "latest"

ingress:
  hosts:
    - host: api-delegation.qa.community.taraxa.io
  tls:
    - secretName: wild-qa-community-taraxa-io-tls
      hosts:
        - api-delegation.qa.community.taraxa.io

resources:
  limits:
    cpu: 540m
    memory: 2048Mi
  requests:
    cpu: 270m
    memory: 750Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-qa