frontend:
  apiHost: "https://api.qa.community.taraxa.io"
  taraAddress: "0xF1ad3aEe148baD0BB1e7c0b7069a130862CC4C0d"
  claimAddress: "0x11D846A8314fBdFcFc8C5f18c5031Bf7a7711938"
  stakingAddress: "0x46Fedb556d84e139846C7401C93fF14D160D4947"
  image:
    repository: gcr.io/jovial-meridian-249123/taraxa-community-frontend-develop
    pullPolicy: Always
    tag: "latest"

  nodeSelector:
    cloud.google.com/gke-nodepool: taraxa-community-qa

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: qa.community.taraxa.io
  tls:
    - secretName: wild-qa-community-taraxa-io-tls
      hosts:
        - qa.community.taraxa.io
